### PR TITLE
Read test models from files instead of hardcoded strings

### PR DESCRIPTION
**Pull request by Scorpiion**
I changed so test models are read in from files instead of hardcoded strings. You had a small todo note there so I assume you were planning to do something similar.

### CODE REVIEW

**Comment by Scorpiion** [comment]
Hi, I have continued working on dogma-data since this pull request was done. 

I have created a tool that takes an input file and generates the needed static lib. I have some things I want to improve but overall it works good. I think you might have had something similar in mind, so I thought I'd tell you so you don't reimplement the same thing.

I pushed up that code in this branch:
https://github.com/Scorpiion/dogma-data/tree/generate

It's a short docs sections down here:
https://github.com/Scorpiion/dogma-data/tree/generate#generate-tool

If you like it I could do a pull request with this new code tomorrow after I tested it some more.

**Comment by donny-dont** [comment]
Looks good! Happy to have you taking a stab at this.

One thing you might want to keep in mind is that the lib might not be in packages. For the tests it would be great if we can generate into a dir and then have it use the relative paths. Not sure if we should assume that if its in lib that then its actually a package of some kind.

Other than that there are a few style nits.
- No space after if
- Using " instead of '
- Using String instead of var in a function

**Comment by Scorpiion** [comment]
Check, got busy with other stuff today so I never got to finish this. 

The way I did it last night when I was testing was to generate a file at the same place as the original file, but with the "_static.dart" prefix. This prefix could be added to a .gitignore if one would not like to check in generated files. Honestly I'm not sure what the best place is to put generated files, one could create some directory and stuff but it might quickly get complicated and/or ugly. I might test and see if there is some better way tomorrow, I plan to setup so I use dogma for all model classes in the project I'm working on right now. 

Either way, I will try to fix so it gets easy generate the files and run the tests. 

I will fix the style part, bad habits.. I have always done the if without spaces, but I will change it of course. :)

**Comment by donny-dont** [comment]
Obsolete pull request so closing it.

**Comment by Scorpiion** [comment]
Sure, sounds good.

**Pull request closed without merging**
